hydra:
  run:
    dir: runs/${task.task}/${model.name}_${name}

name: dev

conf_thres: 0.15      # Confidence threshold for inference (can be overridden on command-line)

defaults:
  - _self_
  - task: train
  - dataset: merged
  - model: mobilenet_pretrained

